from typing import Optional, Union, List
from pydantic import BaseModel, EmailStr

 

class AddressBase(BaseModel):   
    cep: str
    city: str
    estate: str
    adress: str
    number: int
    neighborhood: str
    complement: Optional[str] = None

class BusinessPartnerBase(BaseModel):  
    razao_social: str
    nome_fantasia: str
    cnpj: str
    inscricao_estadual: str
    inscricao_municipal: str
    cnae: str
    suframa: str
    regime_especial: Optional[int] = None
    sugestao_limite_credito: float
    email: str
    phone: str
    observation: Optional[str] = None
    id_address:  AddressBase | Optional[int] = None
    id_company: Optional[int] = None
    IdSynchronizationStatus: Optional[int] = None    

class CompanyBase(BaseModel):  
    razao_social: str
    nome_fantasia: str
    cnpj: str
    email: str
    phone: str
    id_address: Optional[int] = None   
    active: bool

class CompanyAPIConfigurationBase(BaseModel):  
    token: str
    access_json: str

class CompanyPlanConfigurationBase(BaseModel):  
    max_solicitation: int
    valid_until: str

class CompanyBranchBase(BaseModel):  
    name: str
    code: str
    id_company: int
    IdSynchronizationStatus: Optional[int] = None

class CompanyFreightBase(BaseModel):  
    name: str
    code: str
    id_company: int
    IdSynchronizationStatus: Optional[int] = None

class CompanyPaymentMethodBase(BaseModel):  
    name: str
    code: str
    id_company: int
    IdSynchronizationStatus: Optional[int] = None

class CompanyPaymentTermBase(BaseModel):  
    name: str
    code: str
    id_company: int
    IdSynchronizationStatus: Optional[int] = None

class CompanyProductBase(BaseModel):  
    code: str
    name: str
    weight: float
    size: float
    id_company: int
    IdSynchronizationStatus: Optional[int] = None

class CompanyProductStockBase(BaseModel):  
    quantity: float
    code_product: float
    IdSynchronizationStatus: Optional[int] = None
    company_product_id_product: int

class CompanyUtilizationBase(BaseModel):  
    name: str
    code: str
    id_company: int 
    IdSynchronizationStatus: Optional[int] = None

class CompanyHasUserBase(BaseModel):  
    id_company: Optional[int] = None
    id_user: Optional[int] = None

class UserBase(BaseModel):
    username: Optional[str] = None
    email: Optional[EmailStr] = None
    password: Optional[str] = None
    phone: Optional[str] = None
    token: Optional[str] = None 
    role: Optional[str] = None  # 'superadmin', 'admin', 'user'
    company_id: Optional[int] = None
    id_address: Optional[int] = None
    active: Optional[bool] = None

class UserLoginRequest(BaseModel):
    email: EmailStr
    password: str

class UserRegisterRequest(BaseModel):
    username: str
    email: EmailStr
    password: str
    phone: Optional[str] = None

class UserCreateRequest(BaseModel):
    username: str
    email: EmailStr
    password: str
    phone: Optional[str] = None
    role: str = "user"  # Default role
    company_id: Optional[int] = None

class ScreenBase(BaseModel):
    name: str
    description: Optional[str] = None
    route: Optional[str] = None
    active: Optional[bool] = True

class PermissionBase(BaseModel):
    key: str
    name: str
    description: Optional[str] = None
    screen_id: Optional[int] = None
    active: Optional[bool] = True

class UserPermissionBase(BaseModel):
    user_id: int
    permission_id: int

class UserPermissionAssign(BaseModel):
    user_id: int
    permission_keys: List[str]  # Lista de chaves de permissão

class SalesOrderBase(BaseModel):  
    redespacho: int
    data_lancamento: str
    data_entrega: str
    discount: float
    observation: str
    id_company: Optional[int] = None  # Will be set from user's company
    id_business_partner: int
    id_company_payment_method: Optional[int] = None 
    id_company_payment_term: Optional[int] = None 
    id_company_utilization: Optional[int] = None 
    id_company_branch: int
    id_company_freight: Optional[int] = None 
    id_sales_order_redespacho: Optional[int] = None  
    IdSynchronizationStatus: Optional[int] = None 
    created_by_user_id: Optional[int] = None  # Will be set from current user

class SalesOrderCreateRequest(BaseModel):
    redespacho: int = 0
    data_lancamento: Optional[str] = None  # Auto-generated by backend if not provided
    data_entrega: str
    discount: float = 0
    observation: str = ""
    id_business_partner: int
    id_company_payment_method: Optional[int] = None 
    id_company_payment_term: Optional[int] = None 
    id_company_utilization: Optional[int] = None 
    id_company_branch: int
    id_company_freight: Optional[int] = None

class SalesOrderUpdateRequest(BaseModel):
    redespacho: Optional[int] = None
    data_lancamento: Optional[str] = None
    data_entrega: Optional[str] = None
    discount: Optional[float] = None
    observation: Optional[str] = None
    id_business_partner: Optional[int] = None
    id_company_payment_method: Optional[int] = None 
    id_company_payment_term: Optional[int] = None 
    id_company_utilization: Optional[int] = None 
    id_company_branch: Optional[int] = None
    id_company_freight: Optional[int] = None

class SalesOrderFilter(BaseModel):
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    created_by: Optional[int] = None
    business_partner_id: Optional[int] = None
    status: Optional[str] = None 

class SalesOrderProductBase(BaseModel):  
    code: str
    name: str
    data_lancamento: str
    data_entrega: str 
    weight: Optional[float] = None 
    size: Optional[float] = None  
    quantity: float
    discount: float
    price: float
    estoque: Optional[float] = None
    id_sales_order: int

class SalesOrderRedespachoBase(BaseModel):  
    cnpj: str
    nome_transportadora: str
    id_address: int

class SynchronizationStatusBase(BaseModel):  
    status: str
    error: str
    code_error: str
 

class CreateCompanyRequest(BaseModel):
    CompanyBase: CompanyBase
    AddressBase: AddressBase